name = "form-test"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[[kv_namespaces]]
binding = "MY_KV_STORE"
id = "131140ad44d642d58e073a2bbf4c470f"

[[send_email]]
name = "EMAIL"

[[routes]]
pattern = "form-test.s31.dev"
custom_domain = true
